### ISSUE TITLE
tracking point demo error

### ISSUE THREAD

**Issue by jiangziben** [IDEA-Research/TAPTR#5]
i test tracking point demo in 2080Ti,but get error info below, could you help me how to fix this problem?
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.99 GiB (GPU 0; 10.75 GiB total capacity; 8.28 GiB already allocated; 1.59 GiB free; 8.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by LHY-HongyangLi** [comment]
Hy @jiangziben , thanks for your attention. 
This error is due to the memory of your GPU is smaller than the requirement. You can refer to this answer for help temporally:  https://github.com/IDEA-Research/TAPTR/issues/4#issuecomment-2262200153

**Comment by LHY-HongyangLi** [comment]
Hi @jiangziben ,
This issue has been fixed, please refer to this https://github.com/IDEA-Research/TAPTR/issues/4#issuecomment-2264277331

**Comment by LHY-HongyangLi** [comment]
I will close this issue, if you have any questions, feel free to reopen this issue.
